### ISSUE TITLE
Same erros as mentioned

### ISSUE THREAD

**Issue by gene1224** [tbb/pyRC5#2]
`L[i // self.w8] = (L[i // self.w8] << 8) + self.key[i]`
adding int and string please update your code this is just a minor error.

**Comment by tbb** [comment]
key isn't a string. It's bytes
soo
that example can explain better than me
![default](https://cloud.githubusercontent.com/assets/14029507/15721313/1bbfc6d0-2841-11e6-936f-2e7a2fe5a456.PNG)
